#!/bin/bash
set -eu

detach=""
if [ "${1:-}" == "detach" ]; then
  detach="--detach"
fi

HOST_BIND_PORT=8080
CONTAINER_BIND_PORT=8080
# NOTE: To avoid getting blocked by the API, use a valid user agent!
# Read the terms of service and FAQ of api.met.no:
# - https://api.met.no/doc/TermsOfService
# - https://api.met.no/doc/FAQ
PROXY_USER_AGENT=${PROXY_USER_AGENT:-https://github.com/cyberang3l/met.api.no-proxy}
DEBUG=${DEBUG:-0}

docker stop met-proxy 2>/dev/null >/dev/null || true
docker build --target prog_runtime \
  --tag met-proxy .
docker run --name met-proxy \
  ${detach} \
  --rm \
  --publish "${HOST_BIND_PORT}:${CONTAINER_BIND_PORT}/tcp" \
  --env BIND_PORT="${CONTAINER_BIND_PORT}" \
  --env PROXY_USER_AGENT="${PROXY_USER_AGENT}" \
  --env DEBUG="${DEBUG}" \
  met-proxy
